// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AnimationName': string;
  'mainView': string;
  'representationGreen': string;
  'representationHolder': string;
  'representationRed': string;
}
export const cssExports: CssExports;
export default cssExports;
